image: alpine:3.19

before_script:
  - apk add python3 py3-pip
  - python3 -m venv .venv
  - . ./.venv/bin/activate
  - python3 -m pip install -r requirements.txt

cache:
  paths:
    - ~/.cache/pip
    - .venv

stages:
  - ver
  - pretest
  - test

ver:
  stage: ver
  script:
    - python3 --version
    - whoami

pretest:
  stage: pretest
  script:
    - flask --app mobility --debug routes

tests:
  stage: test
  script:
    - python3 -m unittest discover -v -s ./mobility/tests
